#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# solarized dark directory colors
eval `gdircolors ~/.dir_colors`

# custom shell prompt via promptline.vim
source ~/.shell_prompt.sh

# set up z: https://github.com/rupa/z
source /usr/local/etc/profile.d/z.sh

# ignoreeof forces the user to type exit or logout, instead of just pressing ^d
setopt ignoreeof

# execute the line directly when performing history expansion, instead of
# performing the expansion and then reloading the line into the buffer
setopt nohistverify

# don't print an error if a pattern for filename generation has no matches
# fixes adding files to git with wildcards (e.g. via gaa)
unsetopt NOMATCH

# nicer history
alias history="history 0"
export HISTSIZE=100000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

# set vim as the default editor
export EDITOR='vim'
export VISUAL=${EDITOR}

# fzf
export FZF_DEFAULT_COMMAND='rg -i --files --hidden --follow --glob "!.git/*" --glob "!.DS_Store/*" --glob "!node_modules/*"'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# go
export GOPATH="$HOME/gocode"

# java
export JAVA_HOME=$(/usr/libexec/java_home)

# maven
export MAVEN="/usr/local/Cellar/maven/3.3.3/bin"

# user configuration
export PATH="${HOME}/bin:${GOPATH}/bin:${MAVEN}:/usr/local/Cellar/scala/2.11.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"

# vim
alias v='vim'

# fzf integration with z
unalias z 2> /dev/null
z() {
  [ $# -gt 0 ] && _z "$*" && return
  cd "$(_z -l 2>&1 | fzf --height 40% --reverse --inline-info +s --tac --query "$*" | sed 's/^[0-9,.]* *//')"
}

# git aliases
alias gaa='git add --all'
alias gc='git commit --verbose'
alias gca='git commit --amend --verbose'
alias gco='git checkout'
alias gd='git diff'
alias gdh='git diff head'
alias gl='git l'
alias gp='git pull'
alias gpr='git pull --rebase origin master'
alias gr='git r'
alias grm='git branch --merged master | grep -v "\* master" | xargs -n 1 git branch -d'
alias gs='git status'
alias gum="echo 'Resetting master to the latest origin/master...' && git fetch && git update-ref refs/heads/master origin/master"
